### PR TITLE
Element Text: ArrayList to object array

### PR DESCRIPTION
**Pull request by chris3105x**
this adds a setter for the text

### CODE REVIEW

**Comment by Phoenix616** [comment]
Tbh. I'm not too keen on adding such simple helper constructors/methods. I don't really see a lot of reason why anyone using the library couldn't just call the `toArray` themselves? Is there some more reason behind adding this than avoiding that single call?

**Comment by chris3105x** [comment]
In my case it saves a lot of code repetitions. I also think that it is a common practice to get a List from a file to set the lore.
Atleast the constructor would be really useful.

**Comment by Phoenix616** [comment]
I'm unsure why you would use a list for lore/item texts especially when getting it from the config. Doesn't it make way more sense to simply use a multiline string?

**Comment by chris3105x** [comment]
Probably, but you have to split the string. If you save it as a list you can easily set the name and lore without manipulating the data. (YamlConfiguration#getStringList)
In my opinion, a line separator could be confusing for many users.

**Comment by Phoenix616** [comment]
You don't need to split the string, that is already done in the `setItemText` method itself. The setter as well as the constructor accept single strings with new lines as well as arrays (or none at all as it's a vararg and the whole point of it being one is so that there doesn't need to be separate setters and constructors for all three use cases).

And I highly recommend using [YAML's extensive multiline syntax](https://yaml-multiline.info/) instead of some limited implementation with lists for lines for YAML configs.

**Comment by chris3105x** [comment]
I'll have a look at it!
Thank you.

**Pull request closed without merging**
