### PR TITLE
Add clearElements on GuiElementGroup

### PR DESCRIPTION
**Pull request by loidsemus**
I'm not sure if this messes up getSlotIndex and similar methods later and if you need to do more stuff, but this seems to work fine in the testing I've done

### CODE REVIEW

**Comment by Phoenix616** [comment]
Looks like it should be fine. Don't think clearing the slot indexes on the element is necessary for anything, the only potential issue I could think of is if the same element is added multiple times but that's not really supported and probably would lead to other issues too. Might even be good to also set the gui field to null seeing as the element wouldn't be part of the GUI anymore.

And if we really want to support elements that are part of a GUI multiple times or multiple GUIs at once (which I'm not too sure is a good idea to begin with) then that would need to add proper support for it in that change.

**Comment by loidsemus** [comment]
I just needed a way to remove all elements from a group, so that I can then readd different stuff.

Are you saying that just clearing the list (elements.clear()) would suffice for that or do I have to do anything else before?

**Comment by Phoenix616** [comment]
I believe only clearing it should be enough, yes. Unless the plugin using the library references the elements somewhere else they are only ever referenced in the GuiElementGroup list itself so leaving the slots in their list shouldn't be doing anything.

**Comment by loidsemus** [comment]
Alright, should be ready to merge now

**Pull request merged**
