### PR TITLE
Add GuiBackElement

### PR DESCRIPTION
**Pull request by loidsemus**
Add an element that won't show if there's no history and go back to the previous gui if there is

### CODE REVIEW

**Comment by Phoenix616** [comment]
Interesting idea, I usually just handle that manually.

I have a bit of an issue with drawing the GUI twice just for updating the back element in the [show method](https://github.com/Phoenix616/InventoryGui/blob/master/src/main/java/de/themoep/inventorygui/InventoryGui.java#L403-L426) though. Ideally the information whether or not we have something to go back to would be present at the time of the first draw of the GUI already, drawing it twice on each GUI open seems a bit wasteful.

**Comment by loidsemus** [comment]
I already am checking if the history is empty or has only one entry, and if so just draw the filler. Issue with that is that when getItem is called on the element, the history hasn’t been updated yet, so it works fine when you click it but doesn’t show because the history isn’t updated when drawn (when getItem is called) but is updated when you click it. 

The best solution while also avoiding drawing twice is probably just to make sure the history has been updated before doing any drawing at all. I did try to do it that way but didn’t get it to work (didn’t really give it much time, just saw getItem get called somewhere and moved the draw call that was before it to after it instead) so I settled for this. Shouldn’t be too hard if you look into it a bit further though.

As for the checking on action thing, I for some reason thought no item shown = can’t be clicked but that’s obviously not the case, will fix.

**Comment by loidsemus** [comment]
Seems like another thing that makes this complicated is that the inventory is created in draw(). not show(). Because of that it's not really possible to draw after adding history (without doing it twice), because the inventory has to be created before that, which is done in draw

**Comment by Phoenix616** [comment]
Hm, changing canGoBack to something like this might solve that issue without drawing it again in addHistory:

 ```java
    private boolean canGoBack(HumanEntity who) {
        return InventoryGui.getHistory(who).size() > 1 || (InventoryGui.getHistory(who).size() == 1 && InventoryGui.getHistory(who).peekLast() != getGui())
    }
```
The basic idea here is to check if we have at least two (the current GUI and a previous one) to go back to or, if there is only one GUI in it if that GUI is not the current one (the state that the history will have before adding the new GUI to the history when showing it.

Alternatively the addHIstory could be moved to before the drawing of the GUI, there shouldn't be an issue if the GUI is already open (as that's [checked](https://github.com/Phoenix616/InventoryGui/blob/9e3d3107a1b2b62a6e76aaadc9da0856ffac329b/src/main/java/de/themoep/inventorygui/InventoryGui.java#L534)) and the inventory being null shouldn't be able to happen anways after drawing it before.

**Comment by loidsemus** [comment]
Changing canGoBack to your version seems to do the trick.

**Comment by Phoenix616** [comment]
Thank you for your contributions :)

**Pull request merged**
