### PR TITLE
Allows extensive use of inventory (#18)

### PR DESCRIPTION
**Pull request by weihao**
# Propose to Allow Access to Inventory
The inventory can be extended for devs to handle player inventory events while in InventoryGui created graphical user interfaces if needed.

# Example use
```
   @EventHandler(ignoreCancelled = false, priority = EventPriority.HIGHEST)
    public void onClick(InventoryClickEvent e) {
        // Handles invalid clicks.
        if (e.getSlot() < 0) {
            return;
        }
        // Handles invalid entity.
        if (!(e.getWhoClicked() instanceof Player)) {
            return;
        }
        // Handles empty slot.
        if (e.getCurrentItem() != null && e.getCurrentItem().getType() == (Material.AIR)) {
            return;
        }
        Player player = (Player) e.getWhoClicked();

        if ((InventoryGui.getInventory(player)).equals(e.getInventory())) {
            e.setCancelled(true);
            System.out.println("YOU CLICKED ON THE PLAYER INVENTORY WHILE GUI IS OPEN.");
            // your logics here...
        }
    }
```

### CODE REVIEW

**Comment by Phoenix616** [comment]
I'm not sure if I like exposing the inventory like that as imo. there are multiple flaws from an API viewpoint:

- It would allow direct modification of the inventory in was that the library can't deal with or know about
- It requires one to keep a reference to the originally open GUI object around which could easily leak
- It exposes an implementation detail (although that's not too big of an issue in this case) 

I think I would like a static method which can get a player's currently open gui more (e.g. `InventoryGui#getOpen(HumanEntity)`). Of course that would mean that one needs to keep track of all open GUIs and make sure to properly clean those (easiest would be weak references I guess).

**Comment by weihao** [comment]
> It would allow direct modification of the inventory in ways that the library can't deal with or know about
Yes, that is a valid concern. Modified item stacks will cause unexpected errors in GUI elements.
> It requires one to keep a reference to the originally open GUI object around which could easily leak
Yes, a one-to-one mapping is needed to go from player name to inventory which could cause a memory leak, but GC can handle this relation well.

I like the idea of introducing a static method to get a player's currently opened gui.

**Comment by Phoenix616** [comment]
I just realised there already is a [`Inventory#getOpen(HumanEntity)`](https://docs.phoenix616.dev/inventorygui/de/themoep/inventorygui/InventoryGui.html#getOpen(org.bukkit.entity.HumanEntity)) method as that information is already tracked in the history so that doesn't need to be added separately.

**Comment by weihao** [comment]
@Phoenix616 Tested, and it works like a charm.

I will go ahead and close the PR.

**Pull request closed without merging**
